version: '2.1'
services:
  credit-card-control-client:
    build:
      context: .
      dockerfile: dockerfile.prod
    image: credit-card-control-client
    container_name: credit-card-control-client
    environment: 
      PORT: 80
    ports:
      - 8080:80