orbs:
    heroku: circleci/heroku@1.2.2
version: 2.1
workflows:
    build-deploy:
        jobs:
            - deploy-prod:
                filters:
                    branches:
                        only: master

jobs:
    deploy-prod:
        machine: true
        steps:
            - checkout
            - heroku/install
