orbs:
    heroku: circleci/heroku@1.2.2
version: 2.1
workflows:
    build-deploy:
        jobs:
            - deploy-prod:
                filters:
                    branches:
                        only: master

jobs:
    deploy-prod:
        executor: heroku/default
        steps:
            - checkout
            - heroku/install
            - setup_remote_docker:
                version: 18.06.0-ce
            - run:
                command: |
                    heroku container:login
                    docker build -t registry.heroku.com/credit-card-control-client/web -f dockerfile.prod .
                    docker push registry.heroku.com/credit-card-control-client/web
                    heroku container:release web -a $HEROKU_APP_NAME

